# Find all the available rules by running:
# swiftlint rules
disabled_rules: # rule identifiers to exclude from running
- todo
- multiple_closures_with_trailing_closure
- unused_optional_binding
- function_parameter_count
- vertical_parameter_alignment
- multiline_arguments
- trailing_whitespace

opt_in_rules: # some rules are only opt-in
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- duplicate_imports
- empty_collection_literal
- empty_count
- empty_string
- fatal_error_message
- first_where
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- no_space_in_method_call
- nsobject_prefer_isequal
- overridden_super_call
- private_action
- private_outlet
- reduce_boolean
- redundant_objc_attribute
- redundant_type_annotation
- sorted_first_last
- unused_capture_list
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- unused_setter_value

included: # paths to include during linting. `--path` is ignored if present.
- Back2Basics
- Back2BasicsTests
- Back2BasicsUITests

file_length:
- 600

line_length:
  warning: 300
  error: 400
  ignores_comments: true

indentation: 4

function_body_length:
- 50 # warning
- 100 # error

type_body_length:
- 250 # warning
- 400 # error
  
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: 2 # only min_length
  error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL

cyclomatic_complexity:
  ignores_case_statements: true
  
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)
